name: Submit a question
description: Submit a question, reference, issue, or suggestion.
title: "[Question] "
labels: ["question"]
body:
  - type: input
    id: topic
    attributes:
      label: Topic
      placeholder: e.g. sufficiency, KL divergence, conditional expectation
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: Write your question or suggestion here.
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Links or references
      placeholder: Optional links, references, or related declarations.
